### ISSUE TITLE
Errors in late teens

### ISSUE THREAD

**Issue by hawkjo** [collin5/python-n2w#12]
I'm getting erroneous output for the late teens. Specifically, 15 is skipped and 19 is an empty string:

In [7]: for i in range(1, 21):
   ...:     print n2w.convert(i)
   ...:     
one
two
three
four
five
six
seven
eight
nine
ten
eleven
twelve
thirteen
forteen
sixteen
seventeen
eighteen
nineteen

twenty

**Comment by collin5** [comment]
Hi @hawkjo , thanks for pointing this out. PR #13 should have fixed this issue 👍
